name: stormly
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  cloud_firestore: ^4.16.1
  firebase_auth: ^4.19.1
  firebase_core: ^2.29.0
  flutter:
    sdk: flutter
  geocoding: ^3.0.0
  geolocator: ^11.0.0
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.6.0
  google_maps_flutter_android: ^2.7.0
  http: ^1.2.1
  intl: ^0.19.0
  lottie: ^3.1.0
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  weather: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/
    - assets/images/

  uses-material-design: true
