// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnuOnSp-iwlXz5KnJNVZoPI5Pb826LvvU',
    appId: '1:423718442119:web:835a572f9ee6d84ca65422',
    messagingSenderId: '423718442119',
    projectId: 'stormly-7216e',
    authDomain: 'stormly-7216e.firebaseapp.com',
    storageBucket: 'stormly-7216e.appspot.com',
    measurementId: 'G-KQP7HQLWW4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBamuSgYLaoBcbwR9EEh5iuwrOsLUQz8tE',
    appId: '1:423718442119:android:8f436045c30f5b4aa65422',
    messagingSenderId: '423718442119',
    projectId: 'stormly-7216e',
    storageBucket: 'stormly-7216e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFKMZLLtQ0FEGUFxYIUDmcdnldFCCl1Po',
    appId: '1:423718442119:ios:866a61210ac8a4e5a65422',
    messagingSenderId: '423718442119',
    projectId: 'stormly-7216e',
    storageBucket: 'stormly-7216e.appspot.com',
    iosBundleId: 'com.example.stormly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFKMZLLtQ0FEGUFxYIUDmcdnldFCCl1Po',
    appId: '1:423718442119:ios:7e73c0b17f0dd5e3a65422',
    messagingSenderId: '423718442119',
    projectId: 'stormly-7216e',
    storageBucket: 'stormly-7216e.appspot.com',
    iosBundleId: 'com.example.stormly.RunnerTests',
  );
}
